GET http://localhost:3001/api/v1/employees

###

POST http://localhost:3001/api/v1/employees
Content-Type: application/json

{
  "name": "ESTEBAN ARANZAZU",
  "email": "lopezaranzazuesteban@gmail.com",
  "contact_number": "3103994090",
  "position_id": 3
}

###

GET http://localhost:3001/api/v1/positions

###

POST http://localhost:3001/api/v1/positions
Content-Type: application/json

{
  "name": "BACKEND SOFTWARE DEVELOPER",
}

###

GET http://localhost:3001/api/v1/devices

###

POST http://localhost:3001/api/v1/devices
Content-Type: application/json

{
  "name": "PORTATIL",
  "description": "COMPUTER PORTATIL",
}

###

GET http://localhost:3001/api/v1/pdf
